version: '3.4'

services:
  api_gateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: API_Gateway/Dockerfile

  companyapi:
    image: ${DOCKER_REGISTRY-}companyapi
    build:
      context: .
      dockerfile: CompanyServices/Dockerfile


  stockapi:
    image: ${DOCKER_REGISTRY-}stockapi
    build:
      context: .
      dockerfile: StockServices/Dockerfile

  

